version: "3.8"

services:
  web:
    build: .
    image: jugaldevops/custom-nginx:latest
    container_name: custom-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/opt/nginx
